live_config_reload = true
window.opacity = 1.0

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#666666"
blue = "#5C78FF"
cyan = "#5ac8ff"
green = "#9891FF"
magenta = "#5EA2FF"
red = "#DE72FF"
white = "#ffffff"
yellow = "#A3A0FF"

[colors.cursor]
cursor = "#BAC2DE"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#b5c1ff"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#000D1C"
blue = "#76aaff"
cyan = "#28B9FF"
green = "#8E76FF"
magenta = "#2883FF"
red = "#EF56FF"
white = "#f1f1f1"
yellow = "#8069FF"

[colors.primary]
background = "#0D111a"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#C9CCE6"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#5172a7"
text = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[font]
size = 13

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Light"

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "bold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false
blink_interval = 300
thickness = 0.1

[shell]
program = "/usr/bin/zsh"

[window.padding]
x = 20
y = 20
